export default [
  {
    question: 'Who is Tony Stark?',
    a: 'Billionaire',
    b: 'Filantrop',
    c: 'Iron Man',
    d: 'Everything from the above',
    correct: 'd',
  },
  {
    question: 'Who has an ability to strike with lightning?',
    a: 'Jedy',
    b: 'Syth',
    c: 'Mandalorian',
    d: 'Baby Yoda',
    correct: 'b',
  },
  {
    question: 'What is the most expensive staff in the universe of Dune?',
    a: 'Water',
    b: 'Technologies',
    c: 'Spice',
    d: 'Human resources',
    correct: 'c',
  },
  {
    question: 'What does the following proverb mean? "An apple a day, keeps a doctor away"',
    a: 'Eating an apple a day makes you happy',
    b: 'Eating an apple a day makes you healty',
    c: 'Not eating apple a day makes you happy',
    d: 'Eating an apple day after day before another day makes you feel good',
    correct: 'b',
  },
  {
    question: 'Why do we need to drink water?',
    a: 'to live',
    b: 'to stay hydrated',
    c: 'to be healthy',
    d: 'Everything from the above',
    correct: 'd',
  },
]